# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GogolookExam' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GogolookExam

  pod 'SnapKit'
  pod 'Kingfisher'

  target 'GogolookExamTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GogolookExamUITests' do
    # Pods for testing
  end

end
